server:
  port: 8888
# upload path 
me:
  upload:
    path: D:/blogFile/
spring:
  application:
    name: blog-api
  datasource:
    url: jdbc:mysql://localhost:3306/blob?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    database: 0
    host: 192.168.163.150
    port: 6379
    password: 123456
    timeout: 5000
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  boot:
    admin:
      client:
        url: http://localhost:7000
        username: bobo
        password: 123456
        instance:
          name: blog-api
          service-base-url: http://localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  file: admin-client.log #添加开启admin的日志监控