spring:
  application:
    name: blob-admin
  security: # 配置登录用户名和密码
    user:
      name: bobo
      password: 123456
  boot:  # 不显示admin-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}
      notify:
        mail:
          to: 473420490@qq.com
          from: 473420490@qq.com
  mail:
    password: mjxgxwxmbbexbifa
    host: smtp.qq.com
    username: 473420490@qq.com  
server:
  port: 7000